name: Build and Test

on:
  push:
    branches:
      - main  # nebo název vaší hlavní větve
  pull_request:
    branches:
      - main  # nebo název vaší hlavní větve

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET Framework
        uses: microsoft/setup-msbuild@v1

      - name: Restore NuGet packages
        run: nuget restore VcComHubGUI/VcComHubGUI.sln  # Upravte cestu k souboru .sln

      - name: Build project
        run: msbuild VcComHubGUI/VcComHubGUI.sln /p:Configuration=Release  # Upravte cestu k souboru .sln

      # Volitelně: Přidat krok pro spuštění testů, pokud máte nějaké
      # - name: Run tests
      #   run: dotnet test VcComHub/VcComHubGUI.Tests.dll
